export const LIMIT = 12;

/**
 * @typedef Item
 * @property {number} id
 * @property {string} name
 * @property {string} category
 * @property {string} brand
 * @property {number} price
 * @property {number} rating
 * @property {string} imageUrl
 */

/**
 * @typedef Filters
 * @property {string | null} category
 * @property {string | null} brand
 * @property {number | null} rating
 * @property {number | null} price
 */

export async function getAllCategories() {
  await sleep(1500);

  /** @type Set<string> */
  const empty = new Set();
  const categories = data.reduce((categories, item) => {
    categories.add(item.category);
    return categories;
  }, empty);

  return [...categories.values()];
}

export async function getAllBrands() {
  await sleep(1500);

  /** @type Set<string> */
  const empty = new Set();
  const brands = data.reduce((brands, item) => {
    brands.add(item.brand);
    return brands;
  }, empty);

  return [...brands.values()];
}

/**
 * @param {string} query
 * @param {Filters} filters
 * @param {string} rating
 * @param {string} price
 * @param {number} offset
 * @param {number} limit
 */
export async function findItems(
  query,
  filters,
  rating,
  price,
  offset,
  limit = LIMIT,
) {
  await sleep(1500);

  const priceFilter = isPriceInRange(filters.price);
  const ratingFilter = isRatingInRange(filters.rating);
  const categoryFilter = isCategorySame(filters.category);
  const brandFilter = isBrandSame(filters.brand);
  const queryFilter = isQuerySimilar(query);
  const sortRatingCallback = sortRating(rating);
  const sortPriceCallback = sortPrice(price);

  return data
    .filter(priceFilter)
    .filter(ratingFilter)
    .filter(categoryFilter)
    .filter(brandFilter)
    .filter(queryFilter)
    .sort(sortRatingCallback)
    .sort(sortPriceCallback)
    .slice(Number(offset), Number(offset) + Number(limit));
}

function sortRating(rating) {
  return function (a, b) {
    if (rating === "lowest") {
      return a.rating - b.rating;
    } else if (rating === "highest") {
      return b.rating - a.rating;
    }
  };
}

function sortPrice(price) {
  return function (a, b) {
    if (price === "lowest") {
      return a.price - b.price;
    } else if (price === "highest") {
      return b.price - a.price;
    }
  };
}

/**
 * @param {number | null} range
 */
function isPriceInRange(range) {
  /**
   * @param {Item} item
   */
  return function (item) {
    if (range === null) {
      return true;
    }

    if (item.price > range) {
      return false;
    }

    return true;
  };
}

/**
 * @param {number | null} range
 */
function isRatingInRange(range) {
  /**
   * @param {Item} item
   */
  return function (item) {
    if (range === null) {
      return true;
    }

    if (item.rating > range) {
      return false;
    }

    return true;
  };
}

/**
 * @param {string | null} category
 */
function isCategorySame(category) {
  /**
   * @param {Item} item
   */
  return function (item) {
    if (category === null) {
      return true;
    }

    return item.category === category;
  };
}

/**
 * @param {string | null} brand
 */
function isBrandSame(brand) {
  /**
   * @param {Item} item
   */
  return function (item) {
    if (brand === null) {
      return true;
    }

    return item.brand === brand;
  };
}

/**
 * @param {string} query
 */
function isQuerySimilar(query) {
  /**
   * @param {Item} item
   */
  return function (item) {
    if (query === "") {
      return true;
    }

    return item.name.toLocaleLowerCase().includes(query.toLocaleLowerCase());
  };
}

/**
 * @param {number} millis
 */
async function sleep(millis) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, millis);
  });
}

/**
 * @type Item[]
 */
export const data = [
  {
    id: 1,
    name: "Leather Jacket",
    category: "Electronics",
    brand: "Brand E",
    price: 75.34,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 2,
    name: "Bluetooth Speaker",
    category: "Electronics",
    brand: "Brand G",
    price: 195.16,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    category: "Category 8",
    brand: "Brand O",
    price: 155.8,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 4,
    name: "Bluetooth Speaker",
    category: "Category 47",
    brand: "Brand N",
    price: 199.06,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 5,
    name: "Leather Jacket",
    category: "Category 39",
    brand: "Brand N",
    price: 431.01,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 6,
    name: "Leather Jacket",
    category: "Category 50",
    brand: "Brand J",
    price: 477.68,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    category: "Category 9",
    brand: "Brand E",
    price: 115.35,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 8,
    name: "Smartphone",
    category: "Category 16",
    brand: "Brand F",
    price: 494.18,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 9,
    name: "Wireless Headphones",
    category: "Category 26",
    brand: "Brand O",
    price: 476.84,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 10,
    name: "Leather Jacket",
    category: "Category 22",
    brand: "Brand A",
    price: 387.11,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 11,
    name: "Bluetooth Speaker",
    category: "Category 49",
    brand: "Brand E",
    price: 340.37,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 12,
    name: "Smartphone",
    category: "Category 22",
    brand: "Brand L",
    price: 288.46,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 13,
    name: "Leather Jacket",
    category: "Category 36",
    brand: "Brand G",
    price: 231.65,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 14,
    name: "Smartphone",
    category: "Category 38",
    brand: "Brand B",
    price: 321.81,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 15,
    name: "Running Shoes",
    category: "Category 44",
    brand: "Brand M",
    price: 462.46,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 16,
    name: "Leather Jacket",
    category: "Category 41",
    brand: "Brand B",
    price: 115.28,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 17,
    name: "Running Shoes",
    category: "Category 3",
    brand: "Brand F",
    price: 342.33,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 18,
    name: "Smartphone",
    category: "Category 47",
    brand: "Brand M",
    price: 51.9,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 19,
    name: "Wireless Headphones",
    category: "Category 3",
    brand: "Brand B",
    price: 307.77,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 20,
    name: "Leather Jacket",
    category: "Category 38",
    brand: "Brand K",
    price: 458.87,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 21,
    name: "Bluetooth Speaker",
    category: "Category 19",
    brand: "Brand F",
    price: 236.03,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 22,
    name: "Wireless Headphones",
    category: "Category 29",
    brand: "Brand B",
    price: 320.01,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 23,
    name: "Bluetooth Speaker",
    category: "Category 17",
    brand: "Brand F",
    price: 23.6,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 24,
    name: "Running Shoes",
    category: "Category 23",
    brand: "Brand B",
    price: 98.7,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 25,
    name: "Leather Jacket",
    category: "Category 44",
    brand: "Brand A",
    price: 277.02,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 26,
    name: "Wireless Headphones",
    category: "Category 44",
    brand: "Brand N",
    price: 309.54,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 27,
    name: "Wireless Headphones",
    category: "Category 15",
    brand: "Brand N",
    price: 355.81,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 28,
    name: "Smartphone",
    category: "Category 37",
    brand: "Brand G",
    price: 110.0,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 29,
    name: "Wireless Headphones",
    category: "Category 40",
    brand: "Brand F",
    price: 245.17,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 30,
    name: "Smartphone",
    category: "Category 3",
    brand: "Brand E",
    price: 165.27,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 31,
    name: "Smartphone",
    category: "Category 5",
    brand: "Brand I",
    price: 258.23,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 32,
    name: "Wireless Headphones",
    category: "Category 45",
    brand: "Brand A",
    price: 373.06,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 33,
    name: "Smartphone",
    category: "Category 40",
    brand: "Brand C",
    price: 146.21,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 34,
    name: "Leather Jacket",
    category: "Category 3",
    brand: "Brand O",
    price: 469.61,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 35,
    name: "Wireless Headphones",
    category: "Category 6",
    brand: "Brand H",
    price: 184.42,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 36,
    name: "Running Shoes",
    category: "Category 49",
    brand: "Brand G",
    price: 423.43,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 37,
    name: "Leather Jacket",
    category: "Category 40",
    brand: "Brand L",
    price: 168.6,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 38,
    name: "Wireless Headphones",
    category: "Category 37",
    brand: "Brand I",
    price: 23.94,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 39,
    name: "Leather Jacket",
    category: "Category 4",
    brand: "Brand N",
    price: 362.67,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 40,
    name: "Leather Jacket",
    category: "Category 11",
    brand: "Brand H",
    price: 376.94,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 41,
    name: "Wireless Headphones",
    category: "Category 11",
    brand: "Brand M",
    price: 445.2,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 42,
    name: "Leather Jacket",
    category: "Category 35",
    brand: "Brand G",
    price: 274.75,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 43,
    name: "Smartphone",
    category: "Category 8",
    brand: "Brand J",
    price: 58.22,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 44,
    name: "Smartphone",
    category: "Category 37",
    brand: "Brand C",
    price: 204.87,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 45,
    name: "Bluetooth Speaker",
    category: "Category 27",
    brand: "Brand A",
    price: 223.63,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 46,
    name: "Running Shoes",
    category: "Category 4",
    brand: "Brand I",
    price: 215.9,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 47,
    name: "Leather Jacket",
    category: "Category 23",
    brand: "Brand D",
    price: 322.3,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 48,
    name: "Wireless Headphones",
    category: "Category 48",
    brand: "Brand D",
    price: 341.38,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 49,
    name: "Wireless Headphones",
    category: "Category 22",
    brand: "Brand D",
    price: 255.09,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 50,
    name: "Bluetooth Speaker",
    category: "Category 25",
    brand: "Brand M",
    price: 424.65,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 51,
    name: "Running Shoes",
    category: "Category 44",
    brand: "Brand F",
    price: 382.24,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 52,
    name: "Smartphone",
    category: "Category 41",
    brand: "Brand G",
    price: 378.21,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 53,
    name: "Smartphone",
    category: "Category 44",
    brand: "Brand J",
    price: 87.75,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 54,
    name: "Smartphone",
    category: "Category 30",
    brand: "Brand E",
    price: 449.01,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 55,
    name: "Smartphone",
    category: "Category 16",
    brand: "Brand M",
    price: 114.11,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 56,
    name: "Running Shoes",
    category: "Category 18",
    brand: "Brand D",
    price: 432.78,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 57,
    name: "Smartphone",
    category: "Category 33",
    brand: "Brand K",
    price: 289.43,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 58,
    name: "Leather Jacket",
    category: "Category 13",
    brand: "Brand J",
    price: 81.37,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 59,
    name: "Leather Jacket",
    category: "Category 37",
    brand: "Brand L",
    price: 244.08,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 60,
    name: "Leather Jacket",
    category: "Category 19",
    brand: "Brand K",
    price: 200.15,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 61,
    name: "Leather Jacket",
    category: "Category 27",
    brand: "Brand O",
    price: 72.05,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 62,
    name: "Running Shoes",
    category: "Category 31",
    brand: "Brand E",
    price: 210.94,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 63,
    name: "Leather Jacket",
    category: "Category 38",
    brand: "Brand E",
    price: 458.47,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 64,
    name: "Leather Jacket",
    category: "Category 45",
    brand: "Brand I",
    price: 86.93,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 65,
    name: "Smartphone",
    category: "Category 33",
    brand: "Brand L",
    price: 404.77,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 66,
    name: "Leather Jacket",
    category: "Category 31",
    brand: "Brand E",
    price: 337.52,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 67,
    name: "Running Shoes",
    category: "Category 18",
    brand: "Brand A",
    price: 359.98,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 68,
    name: "Running Shoes",
    category: "Category 40",
    brand: "Brand C",
    price: 189.59,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 69,
    name: "Smartphone",
    category: "Category 7",
    brand: "Brand M",
    price: 211.06,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 70,
    name: "Running Shoes",
    category: "Category 4",
    brand: "Brand N",
    price: 419.69,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 71,
    name: "Running Shoes",
    category: "Category 40",
    brand: "Brand N",
    price: 367.64,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 72,
    name: "Wireless Headphones",
    category: "Category 4",
    brand: "Brand I",
    price: 495.65,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 73,
    name: "Running Shoes",
    category: "Category 38",
    brand: "Brand G",
    price: 267.66,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 74,
    name: "Wireless Headphones",
    category: "Category 28",
    brand: "Brand E",
    price: 300.9,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 75,
    name: "Running Shoes",
    category: "Category 43",
    brand: "Brand G",
    price: 436.85,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 76,
    name: "Running Shoes",
    category: "Category 39",
    brand: "Brand I",
    price: 36.93,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 77,
    name: "Wireless Headphones",
    category: "Category 42",
    brand: "Brand O",
    price: 416.42,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 78,
    name: "Wireless Headphones",
    category: "Category 49",
    brand: "Brand D",
    price: 287.13,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 79,
    name: "Bluetooth Speaker",
    category: "Category 28",
    brand: "Brand C",
    price: 153.22,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 80,
    name: "Leather Jacket",
    category: "Category 22",
    brand: "Brand C",
    price: 31.65,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 81,
    name: "Smartphone",
    category: "Category 7",
    brand: "Brand A",
    price: 279.19,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 82,
    name: "Wireless Headphones",
    category: "Category 8",
    brand: "Brand K",
    price: 182.07,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 83,
    name: "Running Shoes",
    category: "Category 44",
    brand: "Brand N",
    price: 24.01,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 84,
    name: "Bluetooth Speaker",
    category: "Category 26",
    brand: "Brand H",
    price: 285.5,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 85,
    name: "Smartphone",
    category: "Category 25",
    brand: "Brand B",
    price: 248.46,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 86,
    name: "Wireless Headphones",
    category: "Category 9",
    brand: "Brand F",
    price: 31.44,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 87,
    name: "Smartphone",
    category: "Category 19",
    brand: "Brand M",
    price: 235.26,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 88,
    name: "Running Shoes",
    category: "Category 37",
    brand: "Brand J",
    price: 203.53,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 89,
    name: "Running Shoes",
    category: "Category 16",
    brand: "Brand M",
    price: 165.78,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 90,
    name: "Bluetooth Speaker",
    category: "Category 41",
    brand: "Brand A",
    price: 350.66,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 91,
    name: "Running Shoes",
    category: "Category 2",
    brand: "Brand O",
    price: 415.02,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 92,
    name: "Smartphone",
    category: "Category 13",
    brand: "Brand D",
    price: 93.13,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 93,
    name: "Smartphone",
    category: "Category 8",
    brand: "Brand K",
    price: 445.99,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 94,
    name: "Leather Jacket",
    category: "Category 40",
    brand: "Brand K",
    price: 199.72,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 95,
    name: "Smartphone",
    category: "Category 39",
    brand: "Brand E",
    price: 378.83,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 96,
    name: "Wireless Headphones",
    category: "Category 50",
    brand: "Brand F",
    price: 166.54,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 97,
    name: "Wireless Headphones",
    category: "Category 29",
    brand: "Brand M",
    price: 61.1,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 98,
    name: "Running Shoes",
    category: "Category 29",
    brand: "Brand L",
    price: 435.25,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 99,
    name: "Running Shoes",
    category: "Category 9",
    brand: "Brand O",
    price: 85.7,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 100,
    name: "Wireless Headphones",
    category: "Category 20",
    brand: "Brand J",
    price: 407.11,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 101,
    name: "Running Shoes",
    category: "Category 21",
    brand: "Brand E",
    price: 356.92,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 102,
    name: "Smartphone",
    category: "Category 17",
    brand: "Brand E",
    price: 452.77,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 103,
    name: "Smartphone",
    category: "Category 3",
    brand: "Brand D",
    price: 467.71,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 104,
    name: "Running Shoes",
    category: "Category 5",
    brand: "Brand N",
    price: 413.3,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 105,
    name: "Leather Jacket",
    category: "Category 12",
    brand: "Brand E",
    price: 330.95,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 106,
    name: "Wireless Headphones",
    category: "Category 38",
    brand: "Brand I",
    price: 55.27,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 107,
    name: "Smartphone",
    category: "Category 28",
    brand: "Brand E",
    price: 352.63,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 108,
    name: "Running Shoes",
    category: "Category 18",
    brand: "Brand E",
    price: 258.15,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 109,
    name: "Running Shoes",
    category: "Category 17",
    brand: "Brand L",
    price: 104.37,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 110,
    name: "Running Shoes",
    category: "Category 29",
    brand: "Brand J",
    price: 377.44,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 111,
    name: "Leather Jacket",
    category: "Category 13",
    brand: "Brand A",
    price: 145.45,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 112,
    name: "Smartphone",
    category: "Category 25",
    brand: "Brand C",
    price: 367.76,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 113,
    name: "Leather Jacket",
    category: "Category 23",
    brand: "Brand H",
    price: 36.85,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 114,
    name: "Leather Jacket",
    category: "Category 19",
    brand: "Brand K",
    price: 481.22,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 115,
    name: "Bluetooth Speaker",
    category: "Category 5",
    brand: "Brand K",
    price: 208.29,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 116,
    name: "Wireless Headphones",
    category: "Category 5",
    brand: "Brand N",
    price: 96.22,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 117,
    name: "Bluetooth Speaker",
    category: "Category 25",
    brand: "Brand A",
    price: 455.04,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 118,
    name: "Bluetooth Speaker",
    category: "Category 40",
    brand: "Brand A",
    price: 308.23,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 119,
    name: "Running Shoes",
    category: "Category 29",
    brand: "Brand F",
    price: 495.28,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 120,
    name: "Running Shoes",
    category: "Category 28",
    brand: "Brand E",
    price: 458.52,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 121,
    name: "Bluetooth Speaker",
    category: "Category 3",
    brand: "Brand L",
    price: 77.63,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 122,
    name: "Bluetooth Speaker",
    category: "Category 6",
    brand: "Brand K",
    price: 409.26,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 123,
    name: "Smartphone",
    category: "Category 40",
    brand: "Brand B",
    price: 97.64,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 124,
    name: "Leather Jacket",
    category: "Category 30",
    brand: "Brand B",
    price: 20.55,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 125,
    name: "Smartphone",
    category: "Category 24",
    brand: "Brand H",
    price: 96.15,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 126,
    name: "Wireless Headphones",
    category: "Category 1",
    brand: "Brand N",
    price: 347.75,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 127,
    name: "Bluetooth Speaker",
    category: "Category 41",
    brand: "Brand D",
    price: 486.89,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 128,
    name: "Bluetooth Speaker",
    category: "Category 44",
    brand: "Brand N",
    price: 53.95,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 129,
    name: "Leather Jacket",
    category: "Category 39",
    brand: "Brand K",
    price: 382.93,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 130,
    name: "Leather Jacket",
    category: "Category 31",
    brand: "Brand I",
    price: 459.6,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 131,
    name: "Bluetooth Speaker",
    category: "Category 7",
    brand: "Brand N",
    price: 446.29,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 132,
    name: "Wireless Headphones",
    category: "Category 11",
    brand: "Brand I",
    price: 330.32,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 133,
    name: "Smartphone",
    category: "Category 13",
    brand: "Brand H",
    price: 273.86,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 134,
    name: "Running Shoes",
    category: "Category 35",
    brand: "Brand E",
    price: 105.11,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 135,
    name: "Bluetooth Speaker",
    category: "Category 15",
    brand: "Brand G",
    price: 353.96,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 136,
    name: "Bluetooth Speaker",
    category: "Category 31",
    brand: "Brand C",
    price: 395.71,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 137,
    name: "Smartphone",
    category: "Category 4",
    brand: "Brand D",
    price: 208.81,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 138,
    name: "Bluetooth Speaker",
    category: "Category 1",
    brand: "Brand E",
    price: 472.95,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 139,
    name: "Wireless Headphones",
    category: "Category 18",
    brand: "Brand L",
    price: 340.39,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 140,
    name: "Leather Jacket",
    category: "Category 12",
    brand: "Brand H",
    price: 152.61,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 141,
    name: "Running Shoes",
    category: "Category 39",
    brand: "Brand K",
    price: 290.43,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 142,
    name: "Leather Jacket",
    category: "Category 23",
    brand: "Brand G",
    price: 398.07,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 143,
    name: "Smartphone",
    category: "Category 5",
    brand: "Brand E",
    price: 106.46,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 144,
    name: "Wireless Headphones",
    category: "Category 47",
    brand: "Brand H",
    price: 286.9,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 145,
    name: "Wireless Headphones",
    category: "Category 31",
    brand: "Brand O",
    price: 350.8,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 146,
    name: "Smartphone",
    category: "Category 34",
    brand: "Brand E",
    price: 172.14,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 147,
    name: "Leather Jacket",
    category: "Category 27",
    brand: "Brand O",
    price: 483.71,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 148,
    name: "Smartphone",
    category: "Category 18",
    brand: "Brand L",
    price: 92.56,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 149,
    name: "Wireless Headphones",
    category: "Category 27",
    brand: "Brand M",
    price: 52.27,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 150,
    name: "Bluetooth Speaker",
    category: "Category 28",
    brand: "Brand O",
    price: 401.69,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 151,
    name: "Running Shoes",
    category: "Category 43",
    brand: "Brand J",
    price: 287.62,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 152,
    name: "Leather Jacket",
    category: "Category 20",
    brand: "Brand K",
    price: 379.76,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 153,
    name: "Running Shoes",
    category: "Category 2",
    brand: "Brand C",
    price: 399.23,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 154,
    name: "Running Shoes",
    category: "Category 16",
    brand: "Brand I",
    price: 336.99,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 155,
    name: "Running Shoes",
    category: "Category 5",
    brand: "Brand K",
    price: 316.91,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 156,
    name: "Leather Jacket",
    category: "Category 48",
    brand: "Brand B",
    price: 38.67,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 157,
    name: "Wireless Headphones",
    category: "Category 16",
    brand: "Brand H",
    price: 328.13,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 158,
    name: "Bluetooth Speaker",
    category: "Category 20",
    brand: "Brand O",
    price: 393.44,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 159,
    name: "Leather Jacket",
    category: "Category 1",
    brand: "Brand E",
    price: 86.07,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 160,
    name: "Bluetooth Speaker",
    category: "Category 39",
    brand: "Brand F",
    price: 38.34,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 161,
    name: "Bluetooth Speaker",
    category: "Category 3",
    brand: "Brand B",
    price: 213.56,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 162,
    name: "Bluetooth Speaker",
    category: "Category 17",
    brand: "Brand A",
    price: 421.71,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 163,
    name: "Bluetooth Speaker",
    category: "Category 30",
    brand: "Brand E",
    price: 437.71,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 164,
    name: "Wireless Headphones",
    category: "Category 40",
    brand: "Brand A",
    price: 283.6,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 165,
    name: "Leather Jacket",
    category: "Category 16",
    brand: "Brand C",
    price: 238.64,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 166,
    name: "Smartphone",
    category: "Category 2",
    brand: "Brand N",
    price: 41.38,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 167,
    name: "Leather Jacket",
    category: "Category 24",
    brand: "Brand N",
    price: 484.49,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 168,
    name: "Bluetooth Speaker",
    category: "Category 41",
    brand: "Brand O",
    price: 487.83,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 169,
    name: "Running Shoes",
    category: "Category 7",
    brand: "Brand F",
    price: 50.81,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 170,
    name: "Bluetooth Speaker",
    category: "Category 28",
    brand: "Brand K",
    price: 398.87,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 171,
    name: "Bluetooth Speaker",
    category: "Category 45",
    brand: "Brand H",
    price: 225.21,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 172,
    name: "Bluetooth Speaker",
    category: "Category 29",
    brand: "Brand G",
    price: 493.88,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 173,
    name: "Wireless Headphones",
    category: "Category 37",
    brand: "Brand L",
    price: 169.99,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 174,
    name: "Smartphone",
    category: "Category 43",
    brand: "Brand J",
    price: 341.59,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 175,
    name: "Bluetooth Speaker",
    category: "Category 27",
    brand: "Brand C",
    price: 32.05,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 176,
    name: "Smartphone",
    category: "Category 36",
    brand: "Brand E",
    price: 164.76,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 177,
    name: "Smartphone",
    category: "Category 8",
    brand: "Brand G",
    price: 347.4,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 178,
    name: "Leather Jacket",
    category: "Category 4",
    brand: "Brand F",
    price: 373.16,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 179,
    name: "Wireless Headphones",
    category: "Category 13",
    brand: "Brand N",
    price: 161.99,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 180,
    name: "Running Shoes",
    category: "Category 35",
    brand: "Brand O",
    price: 174.51,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 181,
    name: "Bluetooth Speaker",
    category: "Category 39",
    brand: "Brand F",
    price: 170.28,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 182,
    name: "Smartphone",
    category: "Category 7",
    brand: "Brand C",
    price: 296.03,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 183,
    name: "Bluetooth Speaker",
    category: "Category 44",
    brand: "Brand J",
    price: 474.13,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 184,
    name: "Leather Jacket",
    category: "Category 39",
    brand: "Brand G",
    price: 338.28,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 185,
    name: "Wireless Headphones",
    category: "Category 47",
    brand: "Brand N",
    price: 307.2,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 186,
    name: "Smartphone",
    category: "Category 34",
    brand: "Brand M",
    price: 399.6,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 187,
    name: "Wireless Headphones",
    category: "Category 11",
    brand: "Brand I",
    price: 35.48,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 188,
    name: "Bluetooth Speaker",
    category: "Category 8",
    brand: "Brand C",
    price: 107.35,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 189,
    name: "Running Shoes",
    category: "Category 35",
    brand: "Brand C",
    price: 250.56,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 190,
    name: "Leather Jacket",
    category: "Category 32",
    brand: "Brand I",
    price: 107.04,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 191,
    name: "Leather Jacket",
    category: "Category 25",
    brand: "Brand J",
    price: 287.36,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 192,
    name: "Leather Jacket",
    category: "Category 40",
    brand: "Brand D",
    price: 168.57,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 193,
    name: "Running Shoes",
    category: "Category 37",
    brand: "Brand D",
    price: 391.48,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 194,
    name: "Wireless Headphones",
    category: "Category 48",
    brand: "Brand N",
    price: 468.45,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 195,
    name: "Bluetooth Speaker",
    category: "Category 34",
    brand: "Brand M",
    price: 30.53,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 196,
    name: "Smartphone",
    category: "Category 24",
    brand: "Brand J",
    price: 445.3,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 197,
    name: "Leather Jacket",
    category: "Category 4",
    brand: "Brand O",
    price: 366.46,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 198,
    name: "Smartphone",
    category: "Category 32",
    brand: "Brand M",
    price: 247.93,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 199,
    name: "Leather Jacket",
    category: "Category 17",
    brand: "Brand H",
    price: 21.61,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 200,
    name: "Smartphone",
    category: "Category 25",
    brand: "Brand F",
    price: 75.45,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 201,
    name: "Running Shoes",
    category: "Category 2",
    brand: "Brand L",
    price: 480.77,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 202,
    name: "Wireless Headphones",
    category: "Category 43",
    brand: "Brand H",
    price: 463.96,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 203,
    name: "Smartphone",
    category: "Category 9",
    brand: "Brand O",
    price: 292.12,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 204,
    name: "Leather Jacket",
    category: "Category 2",
    brand: "Brand D",
    price: 213.07,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 205,
    name: "Leather Jacket",
    category: "Category 33",
    brand: "Brand L",
    price: 469.78,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 206,
    name: "Wireless Headphones",
    category: "Category 2",
    brand: "Brand D",
    price: 157.32,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 207,
    name: "Wireless Headphones",
    category: "Category 21",
    brand: "Brand L",
    price: 462.01,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 208,
    name: "Running Shoes",
    category: "Category 18",
    brand: "Brand K",
    price: 130.06,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 209,
    name: "Bluetooth Speaker",
    category: "Category 21",
    brand: "Brand A",
    price: 262.71,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 210,
    name: "Wireless Headphones",
    category: "Category 1",
    brand: "Brand N",
    price: 44.24,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 211,
    name: "Wireless Headphones",
    category: "Category 15",
    brand: "Brand C",
    price: 287.71,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 212,
    name: "Running Shoes",
    category: "Category 46",
    brand: "Brand F",
    price: 255.96,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 213,
    name: "Running Shoes",
    category: "Category 4",
    brand: "Brand N",
    price: 409.67,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 214,
    name: "Wireless Headphones",
    category: "Category 35",
    brand: "Brand G",
    price: 333.13,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 215,
    name: "Running Shoes",
    category: "Category 20",
    brand: "Brand F",
    price: 488.57,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 216,
    name: "Smartphone",
    category: "Category 32",
    brand: "Brand K",
    price: 259.08,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 217,
    name: "Wireless Headphones",
    category: "Category 12",
    brand: "Brand A",
    price: 441.31,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 218,
    name: "Wireless Headphones",
    category: "Category 24",
    brand: "Brand I",
    price: 205.62,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 219,
    name: "Wireless Headphones",
    category: "Category 3",
    brand: "Brand B",
    price: 212.66,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 220,
    name: "Running Shoes",
    category: "Category 22",
    brand: "Brand A",
    price: 393.85,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 221,
    name: "Running Shoes",
    category: "Category 27",
    brand: "Brand M",
    price: 472.83,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 222,
    name: "Leather Jacket",
    category: "Category 23",
    brand: "Brand N",
    price: 135.6,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 223,
    name: "Running Shoes",
    category: "Category 10",
    brand: "Brand M",
    price: 167.78,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 224,
    name: "Smartphone",
    category: "Category 1",
    brand: "Brand C",
    price: 475.21,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 225,
    name: "Bluetooth Speaker",
    category: "Category 23",
    brand: "Brand N",
    price: 259.65,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 226,
    name: "Running Shoes",
    category: "Category 30",
    brand: "Brand J",
    price: 197.97,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 227,
    name: "Smartphone",
    category: "Category 18",
    brand: "Brand D",
    price: 459.81,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 228,
    name: "Smartphone",
    category: "Category 3",
    brand: "Brand G",
    price: 429.46,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 229,
    name: "Smartphone",
    category: "Category 13",
    brand: "Brand F",
    price: 471.96,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 230,
    name: "Bluetooth Speaker",
    category: "Category 11",
    brand: "Brand C",
    price: 41.89,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 231,
    name: "Leather Jacket",
    category: "Category 30",
    brand: "Brand M",
    price: 244.49,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 232,
    name: "Smartphone",
    category: "Category 43",
    brand: "Brand M",
    price: 498.44,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 233,
    name: "Running Shoes",
    category: "Category 1",
    brand: "Brand G",
    price: 258.22,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 234,
    name: "Wireless Headphones",
    category: "Category 28",
    brand: "Brand A",
    price: 96.42,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 235,
    name: "Smartphone",
    category: "Category 29",
    brand: "Brand E",
    price: 375.91,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 236,
    name: "Wireless Headphones",
    category: "Category 16",
    brand: "Brand K",
    price: 378.89,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 237,
    name: "Leather Jacket",
    category: "Category 21",
    brand: "Brand B",
    price: 90.82,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 238,
    name: "Wireless Headphones",
    category: "Category 49",
    brand: "Brand J",
    price: 121.09,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 239,
    name: "Running Shoes",
    category: "Category 7",
    brand: "Brand O",
    price: 37.26,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 240,
    name: "Leather Jacket",
    category: "Category 19",
    brand: "Brand A",
    price: 52.95,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 241,
    name: "Leather Jacket",
    category: "Category 18",
    brand: "Brand M",
    price: 287.6,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 242,
    name: "Running Shoes",
    category: "Category 6",
    brand: "Brand B",
    price: 350.54,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 243,
    name: "Running Shoes",
    category: "Category 6",
    brand: "Brand O",
    price: 164.19,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 244,
    name: "Smartphone",
    category: "Category 44",
    brand: "Brand J",
    price: 128.73,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 245,
    name: "Running Shoes",
    category: "Category 9",
    brand: "Brand G",
    price: 100.43,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 246,
    name: "Wireless Headphones",
    category: "Category 6",
    brand: "Brand M",
    price: 294.49,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 247,
    name: "Smartphone",
    category: "Category 37",
    brand: "Brand H",
    price: 456.35,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 248,
    name: "Smartphone",
    category: "Category 50",
    brand: "Brand G",
    price: 190.49,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 249,
    name: "Wireless Headphones",
    category: "Category 30",
    brand: "Brand J",
    price: 439.52,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 250,
    name: "Running Shoes",
    category: "Category 40",
    brand: "Brand C",
    price: 373.19,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 251,
    name: "Wireless Headphones",
    category: "Category 8",
    brand: "Brand E",
    price: 332.19,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 252,
    name: "Bluetooth Speaker",
    category: "Category 31",
    brand: "Brand A",
    price: 350.62,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 253,
    name: "Smartphone",
    category: "Category 4",
    brand: "Brand C",
    price: 271.38,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 254,
    name: "Leather Jacket",
    category: "Category 3",
    brand: "Brand E",
    price: 386.88,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 255,
    name: "Bluetooth Speaker",
    category: "Category 30",
    brand: "Brand D",
    price: 449.27,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 256,
    name: "Leather Jacket",
    category: "Category 17",
    brand: "Brand E",
    price: 110.36,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 257,
    name: "Leather Jacket",
    category: "Category 1",
    brand: "Brand L",
    price: 483.06,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 258,
    name: "Wireless Headphones",
    category: "Category 7",
    brand: "Brand I",
    price: 43.84,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 259,
    name: "Wireless Headphones",
    category: "Category 20",
    brand: "Brand M",
    price: 404.84,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 260,
    name: "Wireless Headphones",
    category: "Category 39",
    brand: "Brand A",
    price: 409.61,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 261,
    name: "Smartphone",
    category: "Category 7",
    brand: "Brand F",
    price: 291.35,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 262,
    name: "Leather Jacket",
    category: "Category 3",
    brand: "Brand G",
    price: 110.52,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 263,
    name: "Bluetooth Speaker",
    category: "Category 42",
    brand: "Brand I",
    price: 219.99,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 264,
    name: "Smartphone",
    category: "Category 39",
    brand: "Brand N",
    price: 252.41,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 265,
    name: "Wireless Headphones",
    category: "Category 24",
    brand: "Brand E",
    price: 386.86,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 266,
    name: "Leather Jacket",
    category: "Category 31",
    brand: "Brand G",
    price: 87.67,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 267,
    name: "Leather Jacket",
    category: "Category 3",
    brand: "Brand C",
    price: 27.37,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 268,
    name: "Bluetooth Speaker",
    category: "Category 18",
    brand: "Brand F",
    price: 434.41,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 269,
    name: "Leather Jacket",
    category: "Category 7",
    brand: "Brand L",
    price: 234.89,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 270,
    name: "Wireless Headphones",
    category: "Category 4",
    brand: "Brand E",
    price: 322.88,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 271,
    name: "Wireless Headphones",
    category: "Category 45",
    brand: "Brand L",
    price: 40.51,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 272,
    name: "Leather Jacket",
    category: "Category 39",
    brand: "Brand G",
    price: 226.73,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 273,
    name: "Smartphone",
    category: "Category 35",
    brand: "Brand I",
    price: 252.28,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 274,
    name: "Smartphone",
    category: "Category 7",
    brand: "Brand C",
    price: 73.6,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 275,
    name: "Smartphone",
    category: "Category 35",
    brand: "Brand F",
    price: 74.82,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 276,
    name: "Wireless Headphones",
    category: "Category 14",
    brand: "Brand J",
    price: 128.83,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 277,
    name: "Leather Jacket",
    category: "Category 46",
    brand: "Brand N",
    price: 153.56,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 278,
    name: "Running Shoes",
    category: "Category 47",
    brand: "Brand I",
    price: 257.1,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 279,
    name: "Running Shoes",
    category: "Category 49",
    brand: "Brand O",
    price: 457.75,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 280,
    name: "Running Shoes",
    category: "Category 43",
    brand: "Brand G",
    price: 70.9,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 281,
    name: "Smartphone",
    category: "Category 44",
    brand: "Brand D",
    price: 312.69,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 282,
    name: "Running Shoes",
    category: "Category 9",
    brand: "Brand H",
    price: 235.19,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 283,
    name: "Smartphone",
    category: "Category 3",
    brand: "Brand D",
    price: 101.27,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 284,
    name: "Bluetooth Speaker",
    category: "Category 3",
    brand: "Brand K",
    price: 141.99,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 285,
    name: "Running Shoes",
    category: "Category 42",
    brand: "Brand L",
    price: 378.73,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 286,
    name: "Smartphone",
    category: "Category 4",
    brand: "Brand L",
    price: 168.3,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 287,
    name: "Wireless Headphones",
    category: "Category 29",
    brand: "Brand D",
    price: 230.99,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 288,
    name: "Leather Jacket",
    category: "Category 25",
    brand: "Brand E",
    price: 140.82,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 289,
    name: "Running Shoes",
    category: "Category 5",
    brand: "Brand O",
    price: 80.09,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 290,
    name: "Leather Jacket",
    category: "Category 14",
    brand: "Brand E",
    price: 92.38,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 291,
    name: "Leather Jacket",
    category: "Category 16",
    brand: "Brand I",
    price: 334.98,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 292,
    name: "Bluetooth Speaker",
    category: "Category 12",
    brand: "Brand E",
    price: 126.02,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 293,
    name: "Running Shoes",
    category: "Category 13",
    brand: "Brand C",
    price: 78.26,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 294,
    name: "Wireless Headphones",
    category: "Category 4",
    brand: "Brand J",
    price: 456.1,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 295,
    name: "Bluetooth Speaker",
    category: "Category 2",
    brand: "Brand G",
    price: 77.27,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 296,
    name: "Smartphone",
    category: "Category 14",
    brand: "Brand N",
    price: 56.96,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 297,
    name: "Bluetooth Speaker",
    category: "Category 12",
    brand: "Brand E",
    price: 284.98,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 298,
    name: "Leather Jacket",
    category: "Category 23",
    brand: "Brand I",
    price: 235.24,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 299,
    name: "Running Shoes",
    category: "Category 28",
    brand: "Brand E",
    price: 22.62,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 300,
    name: "Smartphone",
    category: "Category 31",
    brand: "Brand E",
    price: 39.6,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 301,
    name: "Leather Jacket",
    category: "Category 45",
    brand: "Brand F",
    price: 351.53,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 302,
    name: "Wireless Headphones",
    category: "Category 41",
    brand: "Brand K",
    price: 214.86,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 303,
    name: "Smartphone",
    category: "Category 15",
    brand: "Brand C",
    price: 56.94,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 304,
    name: "Wireless Headphones",
    category: "Category 11",
    brand: "Brand O",
    price: 143.59,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 305,
    name: "Running Shoes",
    category: "Category 6",
    brand: "Brand A",
    price: 91.26,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 306,
    name: "Running Shoes",
    category: "Category 23",
    brand: "Brand D",
    price: 200.95,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 307,
    name: "Wireless Headphones",
    category: "Category 21",
    brand: "Brand I",
    price: 46.84,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 308,
    name: "Leather Jacket",
    category: "Category 25",
    brand: "Brand B",
    price: 477.15,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 309,
    name: "Smartphone",
    category: "Category 24",
    brand: "Brand B",
    price: 422.56,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 310,
    name: "Wireless Headphones",
    category: "Category 48",
    brand: "Brand K",
    price: 207.75,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 311,
    name: "Smartphone",
    category: "Category 42",
    brand: "Brand M",
    price: 390.71,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 312,
    name: "Leather Jacket",
    category: "Category 35",
    brand: "Brand F",
    price: 44.32,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 313,
    name: "Leather Jacket",
    category: "Category 34",
    brand: "Brand G",
    price: 352.15,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 314,
    name: "Leather Jacket",
    category: "Category 45",
    brand: "Brand A",
    price: 173.39,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 315,
    name: "Leather Jacket",
    category: "Category 29",
    brand: "Brand M",
    price: 118.1,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 316,
    name: "Running Shoes",
    category: "Category 47",
    brand: "Brand K",
    price: 77.4,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 317,
    name: "Wireless Headphones",
    category: "Category 33",
    brand: "Brand G",
    price: 301.16,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 318,
    name: "Bluetooth Speaker",
    category: "Category 48",
    brand: "Brand G",
    price: 150.13,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 319,
    name: "Wireless Headphones",
    category: "Category 4",
    brand: "Brand E",
    price: 272.39,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 320,
    name: "Smartphone",
    category: "Category 13",
    brand: "Brand L",
    price: 99.61,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 321,
    name: "Wireless Headphones",
    category: "Category 26",
    brand: "Brand F",
    price: 300.85,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 322,
    name: "Running Shoes",
    category: "Category 19",
    brand: "Brand A",
    price: 245.33,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 323,
    name: "Running Shoes",
    category: "Category 2",
    brand: "Brand F",
    price: 161.54,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 324,
    name: "Running Shoes",
    category: "Category 18",
    brand: "Brand B",
    price: 54.9,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 325,
    name: "Bluetooth Speaker",
    category: "Category 26",
    brand: "Brand G",
    price: 465.26,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 326,
    name: "Running Shoes",
    category: "Category 44",
    brand: "Brand K",
    price: 317.54,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 327,
    name: "Smartphone",
    category: "Category 21",
    brand: "Brand C",
    price: 117.02,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 328,
    name: "Leather Jacket",
    category: "Category 23",
    brand: "Brand E",
    price: 24.11,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 329,
    name: "Running Shoes",
    category: "Category 49",
    brand: "Brand J",
    price: 389.73,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 330,
    name: "Leather Jacket",
    category: "Category 44",
    brand: "Brand F",
    price: 169.87,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 331,
    name: "Smartphone",
    category: "Category 14",
    brand: "Brand E",
    price: 265.46,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 332,
    name: "Leather Jacket",
    category: "Category 37",
    brand: "Brand G",
    price: 70.97,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 333,
    name: "Wireless Headphones",
    category: "Category 46",
    brand: "Brand H",
    price: 304.67,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 334,
    name: "Wireless Headphones",
    category: "Category 2",
    brand: "Brand B",
    price: 97.75,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 335,
    name: "Smartphone",
    category: "Category 4",
    brand: "Brand C",
    price: 333.34,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 336,
    name: "Smartphone",
    category: "Category 39",
    brand: "Brand J",
    price: 329.33,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 337,
    name: "Leather Jacket",
    category: "Category 17",
    brand: "Brand M",
    price: 426.04,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 338,
    name: "Running Shoes",
    category: "Category 29",
    brand: "Brand F",
    price: 251.14,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 339,
    name: "Running Shoes",
    category: "Category 3",
    brand: "Brand J",
    price: 389.45,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 340,
    name: "Running Shoes",
    category: "Category 28",
    brand: "Brand K",
    price: 140.25,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 341,
    name: "Running Shoes",
    category: "Category 33",
    brand: "Brand D",
    price: 191.52,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 342,
    name: "Bluetooth Speaker",
    category: "Category 31",
    brand: "Brand B",
    price: 456.13,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 343,
    name: "Wireless Headphones",
    category: "Category 30",
    brand: "Brand G",
    price: 84.66,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 344,
    name: "Smartphone",
    category: "Category 24",
    brand: "Brand H",
    price: 112.27,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 345,
    name: "Leather Jacket",
    category: "Category 47",
    brand: "Brand F",
    price: 84.86,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 346,
    name: "Leather Jacket",
    category: "Category 4",
    brand: "Brand E",
    price: 72.93,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 347,
    name: "Bluetooth Speaker",
    category: "Category 26",
    brand: "Brand J",
    price: 390.35,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 348,
    name: "Bluetooth Speaker",
    category: "Category 15",
    brand: "Brand J",
    price: 61.17,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 349,
    name: "Wireless Headphones",
    category: "Category 23",
    brand: "Brand H",
    price: 66.39,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 350,
    name: "Smartphone",
    category: "Category 20",
    brand: "Brand E",
    price: 160.88,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 351,
    name: "Leather Jacket",
    category: "Category 39",
    brand: "Brand D",
    price: 83.1,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 352,
    name: "Smartphone",
    category: "Category 43",
    brand: "Brand E",
    price: 485.13,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 353,
    name: "Bluetooth Speaker",
    category: "Category 42",
    brand: "Brand M",
    price: 410.99,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 354,
    name: "Smartphone",
    category: "Category 17",
    brand: "Brand G",
    price: 56.98,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 355,
    name: "Running Shoes",
    category: "Category 17",
    brand: "Brand O",
    price: 414.01,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 356,
    name: "Leather Jacket",
    category: "Category 48",
    brand: "Brand O",
    price: 244.24,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 357,
    name: "Leather Jacket",
    category: "Category 38",
    brand: "Brand D",
    price: 22.0,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 358,
    name: "Leather Jacket",
    category: "Category 29",
    brand: "Brand D",
    price: 497.37,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 359,
    name: "Leather Jacket",
    category: "Category 49",
    brand: "Brand O",
    price: 481.51,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 360,
    name: "Smartphone",
    category: "Category 18",
    brand: "Brand J",
    price: 195.3,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 361,
    name: "Bluetooth Speaker",
    category: "Category 50",
    brand: "Brand J",
    price: 200.95,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 362,
    name: "Leather Jacket",
    category: "Category 47",
    brand: "Brand L",
    price: 387.93,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 363,
    name: "Wireless Headphones",
    category: "Category 45",
    brand: "Brand G",
    price: 40.6,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 364,
    name: "Smartphone",
    category: "Category 19",
    brand: "Brand G",
    price: 201.32,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 365,
    name: "Wireless Headphones",
    category: "Category 17",
    brand: "Brand H",
    price: 403.14,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 366,
    name: "Wireless Headphones",
    category: "Category 29",
    brand: "Brand B",
    price: 449.01,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 367,
    name: "Smartphone",
    category: "Category 19",
    brand: "Brand F",
    price: 247.74,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 368,
    name: "Smartphone",
    category: "Category 39",
    brand: "Brand G",
    price: 387.76,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 369,
    name: "Wireless Headphones",
    category: "Category 25",
    brand: "Brand M",
    price: 224.23,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 370,
    name: "Running Shoes",
    category: "Category 31",
    brand: "Brand F",
    price: 229.44,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 371,
    name: "Running Shoes",
    category: "Category 36",
    brand: "Brand I",
    price: 144.67,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 372,
    name: "Bluetooth Speaker",
    category: "Category 29",
    brand: "Brand C",
    price: 257.28,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 373,
    name: "Wireless Headphones",
    category: "Category 3",
    brand: "Brand G",
    price: 273.46,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 374,
    name: "Leather Jacket",
    category: "Category 12",
    brand: "Brand K",
    price: 84.8,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 375,
    name: "Smartphone",
    category: "Category 31",
    brand: "Brand H",
    price: 487.09,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 376,
    name: "Running Shoes",
    category: "Category 6",
    brand: "Brand L",
    price: 214.44,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 377,
    name: "Smartphone",
    category: "Category 2",
    brand: "Brand G",
    price: 29.56,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 378,
    name: "Wireless Headphones",
    category: "Category 22",
    brand: "Brand N",
    price: 246.76,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 379,
    name: "Wireless Headphones",
    category: "Category 29",
    brand: "Brand D",
    price: 288.23,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 380,
    name: "Leather Jacket",
    category: "Category 14",
    brand: "Brand G",
    price: 175.51,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 381,
    name: "Bluetooth Speaker",
    category: "Category 41",
    brand: "Brand G",
    price: 92.83,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 382,
    name: "Bluetooth Speaker",
    category: "Category 5",
    brand: "Brand K",
    price: 163.99,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 383,
    name: "Running Shoes",
    category: "Category 18",
    brand: "Brand A",
    price: 467.28,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 384,
    name: "Wireless Headphones",
    category: "Category 20",
    brand: "Brand I",
    price: 390.03,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 385,
    name: "Wireless Headphones",
    category: "Category 32",
    brand: "Brand G",
    price: 370.25,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 386,
    name: "Running Shoes",
    category: "Category 15",
    brand: "Brand J",
    price: 140.76,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 387,
    name: "Wireless Headphones",
    category: "Category 32",
    brand: "Brand J",
    price: 464.9,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 388,
    name: "Running Shoes",
    category: "Category 8",
    brand: "Brand D",
    price: 383.4,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 389,
    name: "Bluetooth Speaker",
    category: "Category 11",
    brand: "Brand J",
    price: 450.21,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 390,
    name: "Running Shoes",
    category: "Category 29",
    brand: "Brand H",
    price: 201.55,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 391,
    name: "Running Shoes",
    category: "Category 38",
    brand: "Brand D",
    price: 99.29,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 392,
    name: "Smartphone",
    category: "Category 20",
    brand: "Brand H",
    price: 442.72,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 393,
    name: "Running Shoes",
    category: "Category 24",
    brand: "Brand D",
    price: 405.45,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 394,
    name: "Leather Jacket",
    category: "Category 40",
    brand: "Brand F",
    price: 120.17,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 395,
    name: "Leather Jacket",
    category: "Category 40",
    brand: "Brand D",
    price: 324.19,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 396,
    name: "Smartphone",
    category: "Category 34",
    brand: "Brand H",
    price: 315.72,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 397,
    name: "Wireless Headphones",
    category: "Category 48",
    brand: "Brand F",
    price: 315.3,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 398,
    name: "Smartphone",
    category: "Category 24",
    brand: "Brand L",
    price: 85.2,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 399,
    name: "Running Shoes",
    category: "Category 29",
    brand: "Brand H",
    price: 36.48,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 400,
    name: "Leather Jacket",
    category: "Category 49",
    brand: "Brand J",
    price: 418.5,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 401,
    name: "Wireless Headphones",
    category: "Category 22",
    brand: "Brand H",
    price: 239.46,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 402,
    name: "Bluetooth Speaker",
    category: "Category 46",
    brand: "Brand O",
    price: 495.49,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 403,
    name: "Bluetooth Speaker",
    category: "Category 42",
    brand: "Brand B",
    price: 411.58,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 404,
    name: "Bluetooth Speaker",
    category: "Category 31",
    brand: "Brand B",
    price: 191.05,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 405,
    name: "Leather Jacket",
    category: "Category 29",
    brand: "Brand D",
    price: 202.82,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 406,
    name: "Leather Jacket",
    category: "Category 9",
    brand: "Brand C",
    price: 27.34,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 407,
    name: "Running Shoes",
    category: "Category 37",
    brand: "Brand K",
    price: 159.77,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 408,
    name: "Smartphone",
    category: "Category 18",
    brand: "Brand K",
    price: 489.68,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 409,
    name: "Bluetooth Speaker",
    category: "Category 45",
    brand: "Brand F",
    price: 87.64,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 410,
    name: "Bluetooth Speaker",
    category: "Category 7",
    brand: "Brand O",
    price: 127.55,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 411,
    name: "Running Shoes",
    category: "Category 12",
    brand: "Brand N",
    price: 325.49,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 412,
    name: "Wireless Headphones",
    category: "Category 32",
    brand: "Brand I",
    price: 262.8,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 413,
    name: "Wireless Headphones",
    category: "Category 16",
    brand: "Brand J",
    price: 299.39,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 414,
    name: "Running Shoes",
    category: "Category 26",
    brand: "Brand A",
    price: 337.15,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 415,
    name: "Smartphone",
    category: "Category 47",
    brand: "Brand J",
    price: 443.49,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 416,
    name: "Wireless Headphones",
    category: "Category 5",
    brand: "Brand F",
    price: 129.47,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 417,
    name: "Leather Jacket",
    category: "Category 18",
    brand: "Brand L",
    price: 329.66,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 418,
    name: "Smartphone",
    category: "Category 47",
    brand: "Brand H",
    price: 446.72,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 419,
    name: "Running Shoes",
    category: "Category 50",
    brand: "Brand D",
    price: 89.31,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 420,
    name: "Leather Jacket",
    category: "Category 13",
    brand: "Brand A",
    price: 94.7,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 421,
    name: "Wireless Headphones",
    category: "Category 48",
    brand: "Brand N",
    price: 190.82,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 422,
    name: "Wireless Headphones",
    category: "Category 13",
    brand: "Brand D",
    price: 197.41,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 423,
    name: "Running Shoes",
    category: "Category 28",
    brand: "Brand J",
    price: 112.01,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 424,
    name: "Bluetooth Speaker",
    category: "Category 25",
    brand: "Brand O",
    price: 273.16,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 425,
    name: "Wireless Headphones",
    category: "Category 46",
    brand: "Brand I",
    price: 325.78,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 426,
    name: "Leather Jacket",
    category: "Category 49",
    brand: "Brand N",
    price: 80.7,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 427,
    name: "Running Shoes",
    category: "Category 33",
    brand: "Brand K",
    price: 145.73,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 428,
    name: "Leather Jacket",
    category: "Category 48",
    brand: "Brand L",
    price: 59.44,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 429,
    name: "Running Shoes",
    category: "Category 2",
    brand: "Brand O",
    price: 296.78,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 430,
    name: "Bluetooth Speaker",
    category: "Category 9",
    brand: "Brand F",
    price: 463.85,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 431,
    name: "Running Shoes",
    category: "Category 14",
    brand: "Brand G",
    price: 62.8,
    rating: 4.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 432,
    name: "Bluetooth Speaker",
    category: "Category 22",
    brand: "Brand I",
    price: 324.1,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 433,
    name: "Wireless Headphones",
    category: "Category 46",
    brand: "Brand N",
    price: 125.6,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 434,
    name: "Smartphone",
    category: "Category 48",
    brand: "Brand J",
    price: 327.07,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 435,
    name: "Bluetooth Speaker",
    category: "Category 8",
    brand: "Brand A",
    price: 354.1,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 436,
    name: "Running Shoes",
    category: "Category 38",
    brand: "Brand O",
    price: 29.48,
    rating: 5.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 437,
    name: "Leather Jacket",
    category: "Category 48",
    brand: "Brand H",
    price: 102.12,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 438,
    name: "Leather Jacket",
    category: "Category 35",
    brand: "Brand O",
    price: 450.01,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 439,
    name: "Bluetooth Speaker",
    category: "Category 48",
    brand: "Brand C",
    price: 169.05,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 440,
    name: "Bluetooth Speaker",
    category: "Category 42",
    brand: "Brand N",
    price: 349.14,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 441,
    name: "Bluetooth Speaker",
    category: "Category 7",
    brand: "Brand M",
    price: 100.13,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 442,
    name: "Bluetooth Speaker",
    category: "Category 45",
    brand: "Brand K",
    price: 287.01,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 443,
    name: "Running Shoes",
    category: "Category 27",
    brand: "Brand I",
    price: 230.97,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 444,
    name: "Bluetooth Speaker",
    category: "Category 35",
    brand: "Brand L",
    price: 287.35,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 445,
    name: "Leather Jacket",
    category: "Category 38",
    brand: "Brand D",
    price: 152.67,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 446,
    name: "Running Shoes",
    category: "Category 13",
    brand: "Brand B",
    price: 132.98,
    rating: 3.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 447,
    name: "Bluetooth Speaker",
    category: "Category 38",
    brand: "Brand C",
    price: 38.41,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 448,
    name: "Wireless Headphones",
    category: "Category 38",
    brand: "Brand H",
    price: 263.36,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 449,
    name: "Smartphone",
    category: "Category 25",
    brand: "Brand H",
    price: 64.38,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 450,
    name: "Bluetooth Speaker",
    category: "Category 15",
    brand: "Brand A",
    price: 411.04,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 451,
    name: "Leather Jacket",
    category: "Category 42",
    brand: "Brand F",
    price: 217.63,
    rating: 4.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 452,
    name: "Smartphone",
    category: "Category 48",
    brand: "Brand N",
    price: 216.53,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 453,
    name: "Running Shoes",
    category: "Category 2",
    brand: "Brand J",
    price: 363.74,
    rating: 4.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 454,
    name: "Leather Jacket",
    category: "Category 49",
    brand: "Brand J",
    price: 266.09,
    rating: 4.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 455,
    name: "Wireless Headphones",
    category: "Category 20",
    brand: "Brand F",
    price: 86.7,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 456,
    name: "Leather Jacket",
    category: "Category 23",
    brand: "Brand C",
    price: 153.07,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 457,
    name: "Smartphone",
    category: "Category 4",
    brand: "Brand L",
    price: 98.1,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 458,
    name: "Smartphone",
    category: "Category 32",
    brand: "Brand L",
    price: 248.27,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 459,
    name: "Bluetooth Speaker",
    category: "Category 31",
    brand: "Brand O",
    price: 286.11,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 460,
    name: "Wireless Headphones",
    category: "Category 5",
    brand: "Brand F",
    price: 425.99,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 461,
    name: "Bluetooth Speaker",
    category: "Category 3",
    brand: "Brand J",
    price: 172.52,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 462,
    name: "Bluetooth Speaker",
    category: "Category 50",
    brand: "Brand B",
    price: 247.41,
    rating: 3.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 463,
    name: "Smartphone",
    category: "Category 11",
    brand: "Brand I",
    price: 432.31,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 464,
    name: "Wireless Headphones",
    category: "Category 15",
    brand: "Brand D",
    price: 412.83,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 465,
    name: "Running Shoes",
    category: "Category 2",
    brand: "Brand L",
    price: 477.61,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 466,
    name: "Smartphone",
    category: "Category 45",
    brand: "Brand H",
    price: 158.03,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 467,
    name: "Wireless Headphones",
    category: "Category 49",
    brand: "Brand D",
    price: 383.08,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 468,
    name: "Leather Jacket",
    category: "Category 11",
    brand: "Brand N",
    price: 106.08,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 469,
    name: "Running Shoes",
    category: "Category 48",
    brand: "Brand J",
    price: 256.34,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 470,
    name: "Leather Jacket",
    category: "Category 30",
    brand: "Brand F",
    price: 65.2,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 471,
    name: "Bluetooth Speaker",
    category: "Category 1",
    brand: "Brand L",
    price: 305.07,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 472,
    name: "Smartphone",
    category: "Category 24",
    brand: "Brand L",
    price: 28.36,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 473,
    name: "Running Shoes",
    category: "Category 27",
    brand: "Brand O",
    price: 137.14,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 474,
    name: "Bluetooth Speaker",
    category: "Category 26",
    brand: "Brand B",
    price: 343.12,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 475,
    name: "Wireless Headphones",
    category: "Category 30",
    brand: "Brand J",
    price: 379.64,
    rating: 4.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 476,
    name: "Leather Jacket",
    category: "Category 1",
    brand: "Brand K",
    price: 108.29,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 477,
    name: "Bluetooth Speaker",
    category: "Category 44",
    brand: "Brand K",
    price: 234.22,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 478,
    name: "Running Shoes",
    category: "Category 33",
    brand: "Brand F",
    price: 162.6,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 479,
    name: "Bluetooth Speaker",
    category: "Category 1",
    brand: "Brand F",
    price: 48.24,
    rating: 3.0,
    imageUrl: "/medium.webp",
  },
  {
    id: 480,
    name: "Leather Jacket",
    category: "Category 45",
    brand: "Brand K",
    price: 452.79,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 481,
    name: "Bluetooth Speaker",
    category: "Category 21",
    brand: "Brand A",
    price: 32.23,
    rating: 3.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 482,
    name: "Leather Jacket",
    category: "Category 27",
    brand: "Brand I",
    price: 497.78,
    rating: 3.3,
    imageUrl: "/medium.webp",
  },
  {
    id: 483,
    name: "Running Shoes",
    category: "Category 6",
    brand: "Brand O",
    price: 130.87,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 484,
    name: "Wireless Headphones",
    category: "Category 44",
    brand: "Brand O",
    price: 22.68,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 485,
    name: "Leather Jacket",
    category: "Category 8",
    brand: "Brand N",
    price: 141.52,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 486,
    name: "Wireless Headphones",
    category: "Category 17",
    brand: "Brand G",
    price: 254.69,
    rating: 4.8,
    imageUrl: "/medium.webp",
  },
  {
    id: 487,
    name: "Wireless Headphones",
    category: "Category 3",
    brand: "Brand N",
    price: 163.57,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 488,
    name: "Wireless Headphones",
    category: "Category 49",
    brand: "Brand C",
    price: 156.44,
    rating: 4.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 489,
    name: "Running Shoes",
    category: "Category 14",
    brand: "Brand I",
    price: 224.78,
    rating: 3.7,
    imageUrl: "/medium.webp",
  },
  {
    id: 490,
    name: "Bluetooth Speaker",
    category: "Category 40",
    brand: "Brand B",
    price: 497.4,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 491,
    name: "Wireless Headphones",
    category: "Category 4",
    brand: "Brand K",
    price: 416.23,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
  {
    id: 492,
    name: "Bluetooth Speaker",
    category: "Category 2",
    brand: "Brand L",
    price: 421.05,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 493,
    name: "Smartphone",
    category: "Category 17",
    brand: "Brand H",
    price: 497.64,
    rating: 3.9,
    imageUrl: "/medium.webp",
  },
  {
    id: 494,
    name: "Leather Jacket",
    category: "Category 20",
    brand: "Brand H",
    price: 377.73,
    rating: 4.2,
    imageUrl: "/medium.webp",
  },
  {
    id: 495,
    name: "Smartphone",
    category: "Category 40",
    brand: "Brand H",
    price: 352.63,
    rating: 3.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 496,
    name: "Smartphone",
    category: "Category 11",
    brand: "Brand I",
    price: 101.94,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 497,
    name: "Wireless Headphones",
    category: "Category 48",
    brand: "Brand M",
    price: 322.62,
    rating: 4.4,
    imageUrl: "/medium.webp",
  },
  {
    id: 498,
    name: "Bluetooth Speaker",
    category: "Category 22",
    brand: "Brand B",
    price: 201.55,
    rating: 4.6,
    imageUrl: "/medium.webp",
  },
  {
    id: 499,
    name: "Bluetooth Speaker",
    category: "Electronics",
    brand: "Brand E",
    price: 350.77,
    rating: 3.5,
    imageUrl: "/medium.webp",
  },
  {
    id: 500,
    name: "Leather Jacket",
    category: "Electronics",
    brand: "Brand L",
    price: 468.97,
    rating: 3.1,
    imageUrl: "/medium.webp",
  },
];
